### ISSUE TITLE
加入后台服务专属模式

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/Daemon#6]
加入以下3个程序选项
```bash
/usr/bin/node app.js --service #or -s
#使用此选项后没有启动输出，不会启动控制台。
/usr/bin/node app.js --exit #or -e
#为类似systemd的软件提供ExecStop方法。
/usr/bin/node app.js --restart #or -r
#为类似systemd的软件提供ExecRestart方法。
```

**Comment by Suwings** [comment]
准确的说你说的这几条命令，并没有办法很好实现。

node app.js 的意思是启动程序。

一个程序已经运行了，你再运行一个，并且将参数改变怎么可以把原有的程序结束掉呢？

**Comment by KagurazakaNyaa** [comment]
你是希望指定一个类似 --pid=/var/run/mcsm.pid 这种形式的参数来实现吗？

**Comment by Mr-Ao-Dragon** [comment]
> 准确的说你说的这几条命令，并没有办法很好实现。
> 
> node app.js 的意思是启动程序。
> 
> 一个程序已经运行了，你再运行一个，并且将参数改变怎么可以把原有的程序结束掉呢？

我知道，只是寻求能在systemd达到命令表达的效果

**Comment by Mr-Ao-Dragon** [comment]
> 你是希望指定一个类似 --pid=/var/run/mcsm.pid 这种形式的参数来实现吗？

是，systemd写起来还是有缺憾，不能给实例发送主动退出信号，直接killmode=Mixed有数据风险，但只能这么干

**Comment by huangsijun17** [comment]
复议。
systemctl需要root权限。而mcsm在除了docker功能外，没必要给root权限。因此，我是以低权限用户+docker用户组来运行的。这样就导致运行维护mcsm的用户无权开关mcsm的服务……
如果直接运行js就是以服务模式运行，那么也就不需要在维护时额外登录一个管理员用户。

**Comment by Mr-Ao-Dragon** [comment]
> 复议。
> systemd需要root权限。而mcsm在除了docker功能外，没必要给root权限。因此，我是以低权限用户+docker用户组+systemd指定用户来运行的。这样就导致运行维护mcsm的用户无权开关mcsm的服务……
> 如果直接运行js就是以服务模式运行，那么也就不需要在维护时额外登录一个管理员用户。

service start * --user

**Comment by huangsijun17** [comment]
> > 复议。
> > systemd需要root权限。而mcsm在除了docker功能外，没必要给root权限。因此，我是以低权限用户+docker用户组+systemd指定用户来运行的。这样就导致运行维护mcsm的用户无权开关mcsm的服务……
> > 如果直接运行js就是以服务模式运行，那么也就不需要在维护时额外登录一个管理员用户。
> 
> service start * --user

需要设置文件，而且对于ssh连接等不友好，设置、开启麻烦。
