### ISSUE TITLE
Ubuntu 20.04 Docker 生效需要重启 daemon

### ISSUE THREAD

**Issue by PAKingdom** [MCSManager/Daemon#7]
Ubuntu 20.04.3 LTS (GNU/Linux 5.13.0-27-generic x86_64)
截止至2022年2月3日22:42:13 get git pull
版本应该是
web 9.2 发行版
daemon 1.3 发行版
(之前似乎跟[Suwings](https://github.com/Suwings)聊过这个问题了)

**Comment by Suwings** [comment]
你是说先安装面板运行，如果后安装 Docker 要重启 Daemon 程序才可以对吧？这个估计是环境变量未应用到面板上，重启是最简单直接的解决方案，而且只需要一次就行。
