### ISSUE TITLE
docker 端口映射失败

### ISSUE THREAD

**Issue by RimuruChan** [MCSManager/Daemon#8]
简单检查了一下，
端口配置是空的
但是实际上配置了端口

![image](https://user-images.githubusercontent.com/42002296/152648135-a08ea19d-c2fa-442b-9c0d-3aba7af63f88.png)

![image](https://user-images.githubusercontent.com/42002296/152648085-72046d19-65d0-43a8-b002-94911ea3287f.png)

**Comment by RimuruChan** [comment]
看了一下源码实现后面要标/tcp

**Comment by Suwings** [comment]
配置项输入框那里有格式说明。
